### ISSUE TITLE
Does Not Show IPs in Latest Windows 10

### ISSUE THREAD

**Issue by Koolstr** [blakek/zazu-ip-address#6]
I type "ip" in Zazu, but nothing comes up. I remember this worked in the past, but at the very least, in the latest version of Windows 10, it does not seem to be working anymore. Now when I type "ip" nothing shows up. Any ideas?

**Comment by vaidd4** [comment]
Same here, Windows 10 Professional N
`Version 10.0.10586`

In the Plugin Debugger I'm getting this error message : 
```
ERROR: [22:00:28] [blakek/zazu-ip-address :cjayeasw00000psv4kpvslp0x]
Plugin failed to load
{
  "block": "cjayeasw00000psv4kpvslp0x",
  "error": "{ 
    Error: Cannot find module 'has-symbol-support-x'
      at Module._resolveFilename (module.js:455:15)
      at Function.Module._resolveFilename (C:\\Users\\vaidd4\\AppData\\Local\\Programs\\zazu\\resources\\electron.asar\\common\\reset-search-paths.js:35:12)
      at Function.Module._load (module.js:403:25)
      at Module.require (module.js:483:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (C:\\Users\\vaidd4\\.zazu\\plugins\\blakek\\zazu-ip-address\\node_modules\\has-to-string-tag-x\\index.js:19:18)
      at Module._compile (module.js:556:32)
      at Module._extensions..js (module.js:565:10)
      at Object.require.extensions.(anonymous function) [as .js] (C:\\Users\\vaidd4\\AppData\\Local\\Programs\\zazu\\resources\\app.asar\\node_modules\\babel-register\\lib\\node.js:152:7)
      at Module.load (module.js:473:32) code: 'MODULE_NOT_FOUND'
  }",
  "level": "error",
  "message": "Plugin failed to load",
  "plugin": "blakek/zazu-ip-address",
  "time": "2017-12-08T21:00:28.127Z"
}
```

**Comment by vaidd4** [comment]
After hitting `Update Plugins` and retrying entering `ip`, I get this new error : 
`Error: ENOENT: no such file or directory, open 'C:\\Users\\David\\.zazu\\plugins\\blakek\\zazu-ip-address\\node_modules\\isexe\\index.js'`

**EDIT:** Well, I get also these more explicit error: 
```
Error: Cannot find module 'isexe'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\\Users\\vaidd4\\AppData\\Local\\Programs\\zazu\\resources\\electron.asar\\common\\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\\Users\\vaidd4\\.zazu\\plugins\\blakek\\zazu-ip-address\\node_modules\\which\\which.js:10:13)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\\Users\\vaidd4\\AppData\\Local\\Programs\\zazu\\resources\\app.asar\\node_modules\\babel-register\\lib\\node.js:152:7)
    at Module.load (module.js:473:32) code: 'MODULE_NOT_FOUND'
  ```
it seems to be linked to `babel-register` and/or `which` packages

**Comment by Koolstr** [comment]
I resolved this (my case at least). If I were to try to set the options, aka the order of IP's and to include IPv6, it comes up with querying errors in the debugger. That is what I had it set to this whole time. By removing the options array, just `"blakek/zazu-ip-address"` in my config, it works again! 

Odd but not too surprising. Hope this helps anyone else who encounters this issue.
